AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Create S3 Pre-Signed URL
Resources:
  GetPreSignedURL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          BUCKET_NAME: 'smarthouse-userfiles-mobilehub-467026891'
